name: CI

on:
  release:
    types: [ created ]
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx nx affected --target=lint --parallel --max-parallel=2
      - run: npx nx affected --target=test --parallel --max-parallel=2
      - run: npx nx affected --target=build --parallel --max-parallel=2

  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npx nx affected --target=lint --parallel --max-parallel=2
      - run: npx nx affected --target=test --parallel --max-parallel=2
      - run: npx nx affected --target=build --parallel --max-parallel=2

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build:ngx-seo && cd dist/packages/ngx-seo && npm publish --access public && cd -
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
